"""
What is __init__.py?
--------------------
• It is a special Python file
• It tells Python that the folder is a package
• That means Python can import files from this folder

Where is it found?
------------------
Inside project folder and apps

Example:
myproject/
    myproject/
        __init__.py
"""

"""
Simple Meaning:
---------------
• __init__.py = "Hey Python, this is a package folder"

Why is it needed?
-----------------
• Without this file, Python may not treat folder as a module
• Makes import statements work properly

Do we write code inside it?
---------------------------
• Mostly empty
• Sometimes used to add project-level settings
• Beginners usually never edit it
"""
